apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: encryptedsecrets.secret.levigross.com
spec:
  group: secret.levigross.com
  names:
    kind: EncryptedSecret
    listKind: EncryptedSecretList
    plural: encryptedsecrets
    singular: encryptedsecret
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EncryptedSecret is the Schema for the encryptedsecrets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EncryptedSecretSpec defines the desired state of EncryptedSecret
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            data:
              additionalProperties:
                format: byte
                type: string
              description: Data contains the secret data. Each key must consist of
                alphanumeric characters, '-', '_' or '.'. The serialized form of the
                secret data is a base64 encoded string, representing the arbitrary
                (possibly non-string) data value here. Described in https://tools.ietf.org/html/rfc4648#section-4
              type: object
            kind:
              description: 'Kind is a string value representing the REST resource
                this object represents. Servers may infer this from the endpoint the
                client submits requests to. Cannot be updated. In CamelCase. More
                info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata'
              type: object
            stringData:
              additionalProperties:
                type: string
              description: stringData allows specifying non-binary secret data in
                string form. It is provided as a write-only convenience method. All
                keys and values are merged into the data field on write, overwriting
                any existing values. It is never output when reading from the API.
              type: object
            type:
              description: Used to facilitate programmatic handling of secret data.
              type: string
          type: object
        status:
          description: EncryptedSecretStatus defines the observed state of EncryptedSecret
          properties:
            secretStatus:
              items:
                description: KeyStatus is what we use to tell our user about the status
                  of the keys that they have submitted
                type: object
              type: array
          required:
          - secretStatus
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
